---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Palpobaggins"
paths:
  /lakes:
    get:
      description: "Gets `lake` objects.\nOptional query param of **size** determines\n\
        size of returned array\nthis tries to find nearest lakes\n"
      operationId: "lakesGET"
      parameters:
      - name: "size"
        in: "query"
        description: "Size of array"
        required: true
        type: "number"
        format: "double"
      - name: "lat"
        in: "query"
        description: "coordinates"
        required: true
        type: "number"
        format: "double"
      - name: "long"
        in: "query"
        description: "coordinates"
        required: true
        type: "number"
        format: "double"
      responses:
        200:
          description: "Successful response"
      x-swagger-router-controller: "Default"
  /weather:
    get:
      operationId: "weatherGET"
      parameters: []
      responses:
        200:
          description: "asd"
      x-swagger-router-controller: "Default"
definitions: {}
